import { Category, Product, Order } from './definitions';

export const categories: Category[] = [
  { id: 'adesivos', name: 'Adesivos', imageUrl: 'https://picsum.photos/seed/cat1/500/500', imageHint: 'sticker design' },
  { id: 'banners', name: 'Banners', imageUrl: 'https://picsum.photos/seed/cat2/500/500', imageHint: 'conference banner' },
  { id: 'panfletos', name: 'Panfletos', imageUrl: 'https://picsum.photos/seed/cat3/500/500', imageHint: 'flyer mockup' },
  { id: 'placas', name: 'Placas', imageUrl: 'https://picsum.photos/seed/cat4/500/500', imageHint: 'store sign' },
  { id: 'etiquetas', name: 'Etiquetas', imageUrl: 'https://picsum.photos/seed/cat5/500/500', imageHint: 'product label' },
  { id: 'brindes', name: 'Brindes', imageUrl: 'https://picsum.photos/seed/cat6/500/500', imageHint: 'corporate gifts' },
];

export const products: Product[] = [
  {
    id: 'cartao-visita',
    name: 'Cartão de Visita',
    shortDescription: 'Couchê 300g, 4x4 cores, verniz total.',
    description: 'Nossos cartões de visita são produzidos com a mais alta qualidade de impressão em papel Couchê 300g, garantindo um acabamento profissional e duradouro. Personalize com verniz total para um brilho extra ou laminação fosca para um toque sofisticado.',
    imageUrl: 'https://picsum.photos/seed/prod1/600/400',
    imageHint: 'business card',
    basePrice: 89.90,
    category: 'cartoes-visita',
    variations: {
      formats: ['9x5 cm', '8x5 cm'],
      quantities: [100, 500, 1000],
      materials: ['Couchê 250g', 'Couchê 300g', 'Reciclado 240g'],
      colors: ['4x0 (Frente Colorida, Verso Branco)', '4x1 (Frente Colorida, Verso Preto e Branco)', '4x4 (Frente e Verso Coloridos)'],
      finishings: ['Verniz Total Frente', 'Laminação Fosca', 'Corte Especial'],
    },
  },
  {
    id: 'panfleto-a5',
    name: 'Panfleto A5',
    shortDescription: 'Couchê 115g, 4x4 cores.',
    description: 'Divulgue sua empresa com nossos panfletos de alta qualidade. Impressos em papel Couchê 115g, são ideais para distribuição em massa, feiras e eventos. Escolha entre diferentes tamanhos e acabamentos para criar o material perfeito para sua campanha.',
    imageUrl: 'https://picsum.photos/seed/prod2/600/400',
    imageHint: 'flyer design',
    basePrice: 159.90,
    category: 'panfletos',
    variations: {
      formats: ['A5 (14.8x21 cm)', 'A6 (10.5x14.8 cm)'],
      quantities: [500, 1000, 2500],
      materials: ['Couchê 90g', 'Couchê 115g', 'Couchê 150g'],
      colors: ['4x0 (Frente Colorida, Verso Branco)', '4x4 (Frente e Verso Coloridos)'],
      finishings: ['Dobra central', 'Sem acabamento', 'Serrilha'],
    },
  },
  {
    id: 'adesivo-vinil',
    name: 'Adesivo Vinil',
    shortDescription: 'Impressão digital, a prova d\'água.',
    description: 'Nossos adesivos em vinil são perfeitos para personalizar produtos, embalagens, ou para uso como brindes. Com impressão digital de alta resolução e material à prova d\'água, eles são duráveis e versáteis. Disponíveis em diversos formatos e com recorte especial.',
    imageUrl: 'https://picsum.photos/seed/prod3/600/400',
    imageHint: 'vinyl sticker',
    basePrice: 50.00,
    category: 'adesivos',
    variations: {
      formats: ['5x5 cm', '10x10 cm', 'Personalizado'],
      quantities: [100, 250, 500],
      materials: ['Vinil Branco Brilho', 'Vinil Branco Fosco', 'Vinil Transparente'],
      finishings: ['Recorte eletrônico', 'Meio corte', 'Laminação'],
    },
  },
  {
    id: 'banner-rollup',
    name: 'Banner Roll-up',
    shortDescription: 'Lona 440g, com estrutura de alumínio.',
    description: 'O Banner Roll-up é a solução ideal para eventos, feiras e pontos de venda. Fácil de montar e transportar, ele é produzido em lona de alta resistência com impressão de qualidade fotográfica. Acompanha estrutura de alumínio e bolsa para transporte.',
    imageUrl: 'https://picsum.photos/seed/prod4/600/400',
    imageHint: 'rollup banner',
    basePrice: 250.00,
    category: 'banners',
    variations: {
      formats: ['80x200 cm', '100x200 cm'],
      quantities: [1, 2, 5],
      materials: ['Lona Fosca 440g', 'Lona Brilho 440g'],
      finishings: ['Estrutura inclusa'],
    },
  },
  {
    id: 'caneca-personalizada',
    name: 'Caneca Personalizada',
    shortDescription: 'Caneca de cerâmica, 325ml.',
    description: 'Presenteie seus clientes e colaboradores com uma caneca de cerâmica personalizada. Com capacidade de 325ml, ela pode ser estampada com sua marca, fotos ou qualquer arte que desejar. Um brinde útil e que fortalece sua marca no dia a dia.',
    imageUrl: 'https://picsum.photos/seed/prod5/600/400',
    imageHint: 'custom mug',
    basePrice: 35.00,
    category: 'brindes',
    variations: {
      formats: ['325ml'],
      quantities: [1, 10, 50],
      models: ['Branca', 'Mágica', 'Com interior colorido'],
      finishings: ['Caixinha Individual', 'Sem caixinha'],
    },
  },
  {
    id: 'placa-pvc',
    name: 'Placa PVC',
    shortDescription: 'PVC 2mm com adesivo impresso.',
    description: 'Sinalize seu ambiente ou divulgue sua marca com nossas placas de PVC. Leves e resistentes, são produzidas em PVC de 2mm com aplicação de adesivo impresso em alta resolução. Ideais para uso interno e externo.',
    imageUrl: 'https://picsum.photos/seed/cat4/600/400',
    imageHint: 'pvc sign',
    basePrice: 75.00,
    category: 'placas',
     variations: {
      formats: ['30x40 cm', '50x70 cm', 'Personalizado'],
      quantities: [1, 5, 10],
      materials: ['PVC 1mm', 'PVC 2mm', 'PVC 3mm'],
      finishings: ['Furos para fixação', 'Sem furos', 'Fita Dupla Face'],
    },
  },
  {
    id: 'agenda-2025',
    name: 'Agenda 2025',
    shortDescription: 'Capa dura personalizada, miolo padrão.',
    description: 'Organize seu ano com estilo. Nossas agendas 2025 possuem capa dura personalizada, miolo padrão com visão semanal e acabamento em wire-o. Um brinde corporativo excelente para o final de ano.',
    imageUrl: 'https://picsum.photos/seed/prod7/600/400',
    imageHint: 'planner 2025',
    basePrice: 55.00,
    category: 'agendas',
    variations: {
      formats: ['14x20 cm'],
      quantities: [10, 25, 50, 100],
      models: ['Diária', 'Semanal'],
      finishings: ['Wire-o', 'Espiral', 'Elástico para fechar'],
    },
  },
  {
    id: 'calendario-mesa',
    name: 'Calendário de Mesa',
    shortDescription: 'Base em papel triplex, 12 lâminas.',
    description: 'Mantenha sua marca presente na mesa do seu cliente o ano todo. Calendários de mesa com base em papel triplex resistente e 12 lâminas personalizadas, uma para cada mês. Ótima opção de brinde de final de ano.',
    imageUrl: 'https://picsum.photos/seed/prod8/600/400',
    imageHint: 'desk calendar',
    basePrice: 25.00,
    category: 'agendas',
    variations: {
      formats: ['15x10 cm', '20x15 cm'],
      quantities: [50, 100, 250],
      materials: ['Papel Couchê 150g', 'Papel Triplex 300g'],
      finishings: ['Wire-o'],
    },
  },
];

export const orders: Order[] = [
    { id: 'ORD001', customerName: 'Empresa Alpha', customerEmail: 'contato@alpha.com', date: '2024-07-20', total: 189.90, status: 'Entregue', productName: 'Cartão de Visita' },
    { id: 'ORD002', customerName: 'Restaurante Sabor', customerEmail: 'contato@sabor.com', date: '2024-07-22', total: 350.00, status: 'Em produção', productName: 'Panfleto A5' },
    { id: 'ORD003', customerName: 'Loja Beta', customerEmail: 'contato@beta.com', date: '2024-07-23', total: 95.50, status: 'Pronto para retirada', productName: 'Adesivo Vinil' },
    { id: 'ORD004', customerName: 'Hospital Central', customerEmail: 'compras@central.com', date: '2024-07-25', total: 500.00, status: 'Em análise', productName: 'Banner Roll-up' },
    { id: 'ORD005', customerName: 'Empresa Alpha', customerEmail: 'contato@alpha.com', date: '2024-07-28', total: 70.00, status: 'Em produção', productName: 'Caneca Personalizada' },
];
